### ISSUE TITLE
How to know if user has cancelled subscription?

### ISSUE THREAD

**Issue by solojuve1897** [RevenueCat/cordova-plugin-purchases#12]
I first thought that I could look in activeSubscriptions (thinking that if subscription exists it is not cancelled). But I realise now that's wrong. How do I retrieve the information regarding a certain subscription if it has been cancelled by the user?

**Comment by vegaro** [comment]
`activeSubscriptions` will have all subscriptions that have **not expired**. Even if a user cancels, they should still have access to the premium content until the subscription expires. At the moment, we are not surfacing in the SDK if the user has canceled the subscription since most common cases don't rely on this.

Not sure if that answers your question. I am not sure exactly what you are trying to achieve.

**Comment by solojuve1897** [comment]
What I do in my app on a particular page is write "is cancelled on [expiration date]" or "is renewed on [expiration date]". This is how I did it when I used Stripe earlier. But thinking about it now I'm not so sure it's necessary. It's maybe enough just to write "current period [expiration date]". The information about the cancellation will then only be found on the stores.

**Comment by aboedo** [comment]
closing this ticket due to inactivity
