### ISSUE TITLE
Transaction History

### ISSUE THREAD

**Issue by eduardoewgo** [RevenueCat/cordova-plugin-purchases#13]
Right now the _restoreTransactions()_ doesn't have anything related to a history of transactions, only active entitlements/subscriptions and all product identifiers that the user bought so far.

Is there any way to retrieve the transaction history?

**Comment by aboedo** [comment]
Hi! 👋 Sorry for the extremely late reply. I assume that you already figured this out, but I'm replying in case anyone else wonders the same thing: 
There's currently no way to retrieve the full transaction history from the SDK. 
However, `purchaserInfo` does provide you with `allPurchasedProductIdentifiers`, which should give you some information there. It only includes the identifiers, so you won't be able to recompose the full transaction history of the user from there. 

The full transaction history is available through the RevenueCat Dashboard, and you can also get it from ETL exports. 

I'm closing this issue for now, since it's been inactive for quite some time, and we reserve GitHub Issues for bug reports. Feel free to follow up with [RevenueCat Support](support.revenuecat.com) if you need further assistance.
