### ISSUE TITLE
IPA processing failed (ionic 3)

### ISSUE THREAD

**Issue by wingo7** [RevenueCat/cordova-plugin-purchases#43]
Hi, I am using this plugin with ionic 3. I have a problem with creating IPA, during the distribution stage, I have xCode error "IPA processing failed" for ad-hock and enterprise distribution. Also, I am able to see the framework on the embed frameworks in the Xcode. Do you have any suggestions on how to solve it? 
cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.9.2
    ionic (Ionic CLI) : 3.9.2

global packages:

    Cordova CLI : not installed

local packages:

    @ionic/app-scripts : 3.1.8
    Cordova Platforms  : none
    Ionic Framework    : ionic-angular 3.9.1

System:

    Android SDK Tools : 26.1.1
    ios-deploy        : 1.9.4 
    Node              : v8.11.3
    npm               : 5.6.0 
    OS                : macOS
    Xcode             : Xcode 11.3.1 Build version 11C504

**Comment by wingo7** [comment]
/Applications/Xcode.app/Contents/Developer/usr/bin/ipatool exited with 1
2020-06-15 10:32:05 +0000  ipatool JSON: {
    alerts =     (
                {
            code = 3620;
            description = "Configuration issue: platform AppleTVSimulator.platform doesn't have any non-simulator SDKs; ignoring it";
            info =             {
            };
            level = WARN;
        },
                {
            code = 3620;
            description = "Configuration issue: platform WatchSimulator.platform doesn't have any non-simulator SDKs; ignoring it";
            info =             {
            };
            level = WARN;
        },
                {
            code = 3620;
            description = "Configuration issue: platform iPhoneSimulator.platform doesn't have any non-simulator SDKs; ignoring it";
            info =             {
            };
            level = WARN;
        }
    );
}
2020-06-15 10:36:55 +0000 [MT] Canceled distribution assistant

**Comment by aboedo** [comment]
Hi! 👋

This looks like a configuration issue. Would you mind [consulting our support team](https://support.revenuecat.com) to try to figure this out? They're better equipped to figure this kind of issue out. 
FWIW your stack trace looks very similar to the issues mentioned here https://github.com/fastlane/fastlane/issues/15523. If you're using Carthage, make sure that the framework is not embedded through Embed Frameworks. I hope that helps, but feel free to contact our support team if it doesn't. 

We try to reserve github issues for bug reports. I'm closing this since it's a configuration issue.
